### ISSUE TITLE
Remove genuine sites from various blocklists

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard-or-PiHole#61]
**Describe the bug**
Sites containing genuine content being blocked, need to be removed from block lists.

**Additional context**
As follows:

- theconversation.com (in List 4): A genuine news and discussion site
- ghs.googlehosted.com (List 2): this is too broad a block, and is picking up content and application developers who store their information in Google Cloud.
- archive.org (List 1): Internet Archive being blocked
- s3.amazonaws.com (List 3): this is too broad a block, and is picking up content and application developers who store their information in Google Cloud.
- www.apsjobs.gov.au (List 1): Genuine government website
- www.billion.com: website of a modem and network hardware manufacturer
- thepihut.com: Genuine website with content for RPi devices
- fetlife.com (List 2): Inconsistent with filterset tenents, blocking a site of an adult nature
- Afterpay (non-tracking domains), specifically rsx.afterpay.com, static-us.afterpay.com, and static.afterpay.com
- privatelink.msidentity.com: Login service domains for services connected to Microsoft, inc. Office 365, Onedrive, etc.
- www.domain.com.au (List 2): Legitimate site for browing homes for sale and rent.
- nodejs.org (List 3): Legitimate developer site, and AdGuard Home uses nodeJS components.

**Comment by hl2guide** [comment]
ok I'll review this and make some decisions within 10 commits.

**Comment by hl2guide** [comment]
My initial review of this list has been done and I've whitelisted **archive.org**.

For the moment please consider adding them to your own custom whitelist.

A lot these I place in an untrusted anti-customer or privacy invading category but I'll review them again in a few days.
