### ISSUE TITLE
Add CustomSonyTVList

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard-or-PiHole#62]
## Summary
This blocklist blocks smart TV metadata, tracking, and ad traffic for Sony Android TV's; and the same for default applications installed on these devices.

### Blocklist Homepage
https://github.com/twcau/AdblockRules

### Blocklist Link
https://raw.githubusercontent.com/twcau/AdblockRules/master/CustomSonyTVList

**Comment by hl2guide** [comment]
Thanks I'll check it out and decide soon 😃

**Comment by hl2guide** [comment]
Added to the generator, should take affect in the next commit.
