### ISSUE TITLE
Banking sites in Oceania are blocked

### ISSUE THREAD

**Issue by edwin-nz** [hl2guide/Filterlist-for-AdGuard-or-PiHole#63]
When researching banks in the Oceania I notice that the following banks are blocked. 

westpac.com.au - Wespac Bank Australia
commbank.com.au - Commonwealth Bank Australia
westpac.co.nz - Westpac Bank New Zealand
bnz.co.nz - Bank of New Zealand
kiwibank.co.nz - Kiwibank New Zealand
uob.com.sg - United Overseas Bank Singapore
dbs.com.sg - Development Bank of Singapore
dbs.com - Development Bank of Singapore
ocbc.com -  Oversea Chinese Banking Corporation Singapore
posb.com.sg - Post Office Savings Bank Singapore

**Comment by hl2guide** [comment]
ok i'll look over this list tonight 👍
