### ISSUE TITLE
whitelist is in wrong format

### ISSUE THREAD

**Issue by kzshantonu** [hl2guide/Filterlist-for-AdGuard-or-PiHole#64]
It seems like the list is supposed to be of domain.tld and *.domain.tld. But @@|| automatically allow subdomains too. So for example, @@||youtube.com (currently in the list) will whitelist everything.youtube.com. Here's a guide for [adblock syntax](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#adblock-style). So in a nutshell (from what I can understand) @@domain.tld for domain.tld only and @@||domain.tld for anything.domain.tld.

PS: keep up the good work. Oh and my testing was on adguard home

**Comment by hl2guide** [comment]
okay, I'll review this.

**Comment by hl2guide** [comment]
I've reviewed this and it seems fine to me.

e.g.:

`@@||wikimedia.org^$important`

for the above:

`@@` means "allow"
`||` means match beginning
`^` means match end _<== VITAL_
`$important` means take priority over other rules

I'll do a few more checks later today to see that it's taking affect like I infer it does.

**Comment by kzshantonu** [comment]
I can confirm @@||domain.tld whitelists all subdomains too. It's mentioned on the AdGuard's syntax guide that I linked on my first comment
<img width="558" alt="brave_ElHzehaODu" src="https://user-images.githubusercontent.com/7745374/119245529-4f8d5a00-bb7a-11eb-9108-bc0d08ecdc9b.png">

**Comment by kzshantonu** [comment]
@hl2guide mentioning in case you missed it. Regards

**Comment by hl2guide** [comment]
Only just read that now, I don't now why `^` would be ignored.

I'll check this in the next few days and then make adjustments if needed.

**Comment by kzshantonu** [comment]
@hl2guide 
The sonos example is my speakers pinging the metrics server every few minutes. I don't have an URL. I added that custom rule as an example to show how dangerous `@@||domain.tld^$important` can be. I suggest splitting your allowlist into 2. One with just the domains like [this one](https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt) (well-known allowlist used by many). This is safe and ADH will only allow exact matches. And second one in adblock syntax that adguard expects. Anything with wildcard should go into the second one. You'll have to use regex in this one to accomplish proper, safe and intentional whitelisting. I'm not qualified enough for regex but [this](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-regular-expressions-support) should be a good place to start. The blocklists are okay and they block as intended. It's just the whitelist. The goal is to not accidentally whitelist 'too much'

**Comment by hl2guide** [comment]
fair points. i'll look this over for the next few days and then update the whitelist within 3 days.

**Comment by hl2guide** [comment]
Uploaded initial fix for this. I'll be making more changes to it over the next few days.

**Comment by kzshantonu** [comment]
Great I'll add it to my ADH and see what's up
