### ISSUE TITLE
Apis on blocklist

### ISSUE THREAD

**Issue by brurnt** [hl2guide/Filterlist-for-AdGuard-or-PiHole#66]
1. api.twitter.com is on blocklist 1 which blocks image loading on the mobile app.
2. As you say Does not block websites of an "adult nature" there is redgifs.com and api.redgifs.com on the blocklists 3 and 4, which is a big normal adult content platform like pornhub.com. The api e. g. is used on reddit.
And idk why nobody has mentioned it. I think it's because they don't daring to post this but I do 😉
3. Same goes for rule34.xxx

**Comment by hl2guide** [comment]
1) Intentional Social Media Blocking

For sites of an "adult nature" only the mainstream, commonly known ones are whitelisted. Easily whitelisted.
