### ISSUE TITLE
Remove entry for osxapps.itunes.g.aaplimg.com

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard-or-PiHole#67]
**Describe the bug**
Currently in List 3, the block for osxapps.itunes.g.aaplimg.com, which affects osxapps.itunes.apple.com, and is a legitimate content site that is used by OSX devices to obtain software updates.

**Additional context**
Block is an excessive CDN block, site does not knowingly gather telemetry data, nor does it meet another category for this project that would justify a block.

**Comment by hl2guide** [comment]
Ok I'll remove that 👍
