### ISSUE TITLE
suggestion: porn whitelisting disclaimer

### ISSUE THREAD

**Issue by kzshantonu** [hl2guide/Filterlist-for-AdGuard-or-PiHole#68]
I suggest adding a disclaimer on the usage page that the whitelist contain porn domains. I can see someone using blocklists+whitelist from here and an additional porn blocklist from elsewhere to their blocker and not really blocking porn because whitelists override blocklists

**Comment by hl2guide** [comment]
For the moment I think the "Focus" explains enough.
