### ISSUE TITLE
Peter Lowe's blocklist (used by uBlock Origin)

### ISSUE THREAD

**Issue by mrbluecoat** [hl2guide/Filterlist-for-AdGuard-or-PiHole#69]
## Summary
Popular ad block list
### Blocklist Homepage
https://pgl.yoyo.org/adservers/
### Blocklist Link
https://pgl.yoyo.org/adservers/serverlist.php

**Comment by hl2guide** [comment]
Thanks for the suggestion, I'll consider it for the next major commit.

**Comment by hl2guide** [comment]
Just tried testing it out and I get:
Error: control/filtering/add_url | Couldn't fetch filter from url https://pgl.yoyo.org/adservers/serverlist.php?hostformat=plaintext;showintro=0: data is HTML, not plain text | 400

I'll see how Peter responds to my question.

**Comment by mrbluecoat** [comment]
Try https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

**Comment by mrbluecoat** [comment]
Other lists to consider as well: https://github.com/FaserF/adguardhome_lists/blob/master/blocklists

**Comment by mrbluecoat** [comment]
Another resource: https://github.com/anudeepND/blacklist

**Comment by hl2guide** [comment]
Okay, I'm testing: `https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext`
