### ISSUE TITLE
List 1: Odd rule blocking a Govt COVID health site

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard-or-PiHole#71]
**Describe the bug**
List 1 currently has a bizarrely short rule, reporting as `a.a`, triggering a CNAME or IP block for www.healthywa.wa.gov.au, for the following responses:
CNAME: www.healthywa.health.wa.gov.au.edgekey.net. (ttl=60)
CNAME: e32832.dsca.akamaiedge.net. (ttl=21600)
A: 23.47.73.9 (ttl=20)
A: 23.47.73.56 (ttl=20)

![3BCB4101-3914-431D-8467-F3607F71616E](https://user-images.githubusercontent.com/34460650/124117879-39d95180-daa3-11eb-8c38-bbfc1f79ea72.jpeg)

**Comment by hl2guide** [comment]
Thanks for reporting this, I'll look into this tomorrow and resolve it 😸

**Comment by hl2guide** [comment]
Resolved in the next commit.
