### ISSUE TITLE
Whitelist Modules for Social Media

### ISSUE THREAD

**Issue by tyrelius** [hl2guide/Filterlist-for-AdGuard-or-PiHole#74]
## Summary
Please add whitelist modules for different social media sites, such as Twitter, Facebook, Instagram, YouTube, etc.
### Basic example
```
https://github.com/hl2guide/Filterlist-for-AdGuard-or-PiHole/raw/master/Whitelist-Modules/whitelist_for_facebook.txt
https://github.com/hl2guide/Filterlist-for-AdGuard-or-PiHole/raw/master/Whitelist-Modules/whitelist_for_twitter.txt
https://github.com/hl2guide/Filterlist-for-AdGuard-or-PiHole/raw/master/Whitelist-Modules/whitelist_for_instagram.txt
https://github.com/hl2guide/Filterlist-for-AdGuard-or-PiHole/raw/master/Whitelist-Modules/whitelist_for_youtube.txt
```
### Motivation
Why are we doing this? What use cases does it support? What is the expected outcome?
Being able to block as many ads and tracking as possible on social media sites helps increase privacy while these sites are used. Due to the nature of social media, and same-domain tracking, I know not all tracking and ads can be properly blocked from social media sites. However, adding a whitelist module that users can choose to use if they so wish would help users who would like to allow social media sites to load without having to blanket whitelist those services, as well as that some of these services use different content delivery domains that are sometimes hard to know.
For example, these are a few whitelist rules that I have enabled to try to get a few of these services working properly, and I am unsure if some of these are analytics/tracking/ads or not:
```
@@||api.twitter.com^$important
@@||api-stream.twitter.com^$important
@@||ton.twitter.com^$important
@@||abs.twimg.com^$important
@@||pbs.twimg.com^$important
@@||video.twimg.com^$important
@@||i.instagram.com^$important
@@||scontent-*.cdninstagram.com^$important
@@||scontent.cdninstagram.com^$important
@@||graph.instagram.com^$important
@@||instagram.*.facebook.com^$important
@@||www.facebook.com^$important
@@||connect.facebook.net^$important
@@||edge-chat.facebook.com^$important
@@||gateway.facebook.com^$important
@@||edge-mqtt.facebook.com^$important
@@||m.facebook.com^$important
@@||fbcdn.net^$important
@@||static.*.fbcdn.net^$important
@@||scontent.*.fbcdn.net^$important
@@||web.facebook.com^$important
@@||star-mini.*.facebook.com^$important
@@||star.*.facebook.com^$important
@@||msgr-latest.*.facebook.com^$important
# Medium.com seems to be blanket blocked.
@@||medium.com^$important
@@||iosapps.itunes.g.aaplimg.com^$important
@@||guzzoni.apple.com^$important
# gsa.apple.com seems to be used for iCloud login, at least for their Windows client.
@@||gsa.apple.com^$important
```

**Comment by hl2guide** [comment]
Thanks for this suggestion, I'll look into the viability of this and see what can be done.

There will be a delay in me releasing it, as it is complex and difficult for me test as I use no social media sites at all.

**Comment by hl2guide** [comment]
resolved.
